eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry-service:8761/eureka/
  instance:
    hostname: service-registry-service
